@Api_HostAddress = http://localhost:5269

GET {{Api_HostAddress}}/api/
Accept: application/json

###

GET {{Api_HostAddress}}/api/libraries
Accept: application/json

###

GET {{Api_HostAddress}}/api/libraries/1
Accept: application/json

###

POST {{Api_HostAddress}}/api/libraries
Content-Type: application/json

{
    "name": "Tainara Library"
}

###

DELETE {{Api_HostAddress}}/api/libraries/CBA34E82-C5B3-46CF-8B3B-26556B056EEB
Accept: application/json

###

POST {{Api_HostAddress}}/api/libraries/1/books
Content-Type: application/json

[
    {
        "title": "Daisy Jones",
        "author": "Taylor Jenkins Reid"
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides"
    }
]

###
DELETE {{Api_HostAddress}}/api/libraries/1/books/5
Accept: application/json

###
PUT {{Api_HostAddress}}/api/libraries/1/books/2/borrow
Accept: application/json

###
PUT {{Api_HostAddress}}/api/libraries/1/books/2/return

###
GET {{Api_HostAddress}}/api/libraries/1/books?borrowed=false