@Api_HostAddress = http://localhost:5269

GET {{Api_HostAddress}}/api/
Accept: application/json

###

GET {{Api_HostAddress}}/api/libraries
Accept: application/json

###

GET {{Api_HostAddress}}/api/libraries/cba34e82-c5b3-46cf-8b3b-26556b056eeb
Accept: application/json

###

POST {{Api_HostAddress}}/api/libraries
Content-Type: application/json

{
    "name": "Tainara Library"
}

###

DELETE {{Api_HostAddress}}/api/libraries/CBA34E82-C5B3-46CF-8B3B-26556B056EEB
Accept: application/json

###

POST {{Api_HostAddress}}/api/libraries/4f10c512-0eeb-493e-8ab3-4050d2c444c7/books
Content-Type: application/json

[
    {
        "title": "Os 7 maridos de Evelyn Hugo",
        "author": "Taylor Jenkins Reid"
    },
    {
        "title": "Jantar Secreto",
        "author": "Raphael Montes"
    }
]